version: "{build}"

environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 4
    - nodejs_version: 0.12
    - nodejs_version: 0.10

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  # tools versions
  - node --version
  - npm --version
  # install modules
  - npm install

test_script:
  - npm test

build: off