version: "{build}"

environment:
  matrix:
    - nodejs_version: "Stable" # latest
    - nodejs_version: 6
    - nodejs_version: 4
    - nodejs_version: 0.12
    - nodejs_version: 0.10

platform:
  - x64

# master + PRs
branches:
  only:
    - master

install:
  - ps: Install-Product node $env:nodejs_version
  # tools versions
  - node --version
  - npm --version
  # install modules
  - npm install

test_script:
  - npm test

build: off